### PR TITLE
Hexo Integration

### PR DESCRIPTION
**Pull request by timhartmann**
Add Hexo as Static Site Generator

### CODE REVIEW

**Comment by iurimatias** [comment]
hi @timhartmann ,

could you rebase this and move the contents inside packages/docs plz https://github.com/embarklabs/subspace/tree/master/packages/docs

**Comment by timhartmann** [comment]
@iurimatias Why should I put into packages/docs? Hexo needs the source folder instead of packages. And the URLs will go wrong if we do it, I think

**Comment by timhartmann** [comment]
@iurimatias I changed it in the config. Does it be okay now?

**Comment by richard-ramos** [comment]
The main problem I see here is that this commit is removing everything: the subspace core package, react as well as the general configuration for only the new documentation site.
I have a suggestion to fix this:

1. In your fork, create a new branch from master
2. Create a folder:  `./packages/site/`
3. Put the content of the hexo project inside that project (including its package.json, .md files, images, etc).
4. Create a new PR from that branch.

That should avoid the problem this PR has.  

Hexo should be able to run if you navigate in a terminal to ./packages/site and execute the start command there.

**Pull request closed without merging**
